Workforce-Purple-Parrots/Workforce-Purple-Parrots/Models/Computer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Workforce_Purple_Parrots.Models
{
    public class Computer
    {
        public int Id { get; set; }
        public DateTime PurchaseDate { get; set; }
        public DateTime? DecomissionDate { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public Employee? Employee  { get; set; }
    }
}

Workforce-Purple-Parrots/Workforce-Purple-Parrots/Controllers/ComputersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Configuration;
using Workforce_Purple_Parrots.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Workforce_Purple_Parrots.Models.ViewModels;

namespace Workforce_Purple_Parrots.Controllers
{
    public class ComputersController : Controller
    {
        private readonly IConfiguration _config;

        public ComputersController(IConfiguration config)
        {
            _config = config;
        }

        public SqlConnection Connection
        {
            get
            {
                return new SqlConnection(_config.GetConnectionString("DefaultConnection"));
            }
        }

        // GET: Computer
        public ActionResult Index(string searchString)
        {
            using (SqlConnection conn = Connection)
            {
                conn.Open();
                using (SqlCommand cmd = conn.CreateCommand())
                {
                    cmd.CommandText = @"SELECT Id, Make, Model, PurchaseDate, DecomissionDate FROM Computer ";

                    if (!string.IsNullOrEmpty(searchString))
                    {
                        cmd.CommandText += @"WHERE Make LIKE @searchString OR Model LIKE @searchString";
                        cmd.Parameters.Add(new SqlParameter("@searchString", "%" + searchString + "%"));
                    }

                    var reader = cmd.ExecuteReader();
                    var computers = new List<Computer>();

                    while (reader.Read())
                    {
                        var computer = new Computer()
                        {
                            Id = reader.GetInt32(reader.GetOrdinal("Id")),
                            Make = reader.GetString(reader.GetOrdinal("Make")),
                            Model = reader.GetString(reader.GetOrdinal("Model")),
                            PurchaseDate = reader.GetDateTime(reader.GetOrdinal("PurchaseDate"))
                        };


                        if (!reader.IsDBNull(reader.GetOrdinal("DecomissionDate")))
                        {
                            computer.DecomissionDate = reader.GetDateTime(reader.GetOrdinal("DecomissionDate"));


                        };

                        computers.Add(computer);
                    }
                    reader.Close();
                    return View(computers);
                }
            }

        }

        // GET: Computer/Details/5
        public ActionResult Details(int id)
        {
            var computer = GetComputerById(id);
            return View(computer);


        }

        // GET: Computer/Create
        public ActionResult Create()
        {
            var employeeOptions = GetEmployeeOptions();
            var viewModel = new ComputerFormViewModel()
            {
                PurchaseDate = DateTime.Now,
                EmployeeOptions = employeeOptions
            };
            return View(viewModel);
        }

        // POST: Computer/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ComputerFormViewModel computer)
        {
            try
            {
                //if there is an Employee ID value
                //execute an update employee function
                //this will add the new computerId to an existing employee
                //return to indexView
                using (SqlConnection conn = Connection)
                {
                    conn.Open();
                    using (SqlCommand cmd = conn.CreateCommand())
                    {
                        cmd.CommandText = @"INSERT INTO Computer (Make, Model, PurchaseDate)
                                            OUTPUT INSERTED.Id
                                            VALUES (@make, @model, @purchaseDate)";

                        cmd.Parameters.Add(new SqlParameter("@make", computer.Make));
                        cmd.Parameters.Add(new SqlParameter("@model", computer.Model));
                        cmd.Parameters.Add(new SqlParameter("@purchaseDate", computer.PurchaseDate));


                        var id = (int)cmd.ExecuteScalar();
                        computer.Id = id;
                        if (computer.EmployeeId != 0)
                        {
                            //update employee
                            //I will need, the computer.EmployeeId
                            //and I will need the computer.Id
                            UpdateEmployee(computer.Id, computer.EmployeeId);
                        }

                        return RedirectToAction(nameof(Index));
                    }
                }


            }
            catch (Exception ex)
            {
                return View();
            }
        }

        // GET: Computer/Delete/5
        public ActionResult Delete(int id)
        {
            var computer = GetComputerById(id);

            return View(computer);
        }

        // POST: Computer/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Computer computer)
        {
            try
            {
                using (SqlConnection conn = Connection)
                {
                    conn.Open();
                    using (SqlCommand cmd = conn.CreateCommand())
                    {
                        cmd.CommandText = "DELETE FROM Computer WHERE Id = @id";
                        cmd.Parameters.Add(new SqlParameter("@id", computer.Id));

                        cmd.ExecuteNonQuery();
                    }
                }

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewData["ErrorMessage"] = "Cannot Delete Computer that has been assigned to a user.";
                return View(computer);
            }
        }

        private List<SelectListItem> GetEmployeeOptions()
        {
            using (SqlConnection conn = Connection)
            {
                conn.Open();
                using (SqlCommand cmd = conn.CreateCommand())
                {
                    cmd.CommandText = "SELECT Id, COALESCE(FirstName + ' ' + LastName, 'N/A') as EmployeeName FROM Employee";

                    var reader = cmd.ExecuteReader();
                    var options = new List<SelectListItem>();

                    while (reader.Read())
                    {
                        var option = new SelectListItem()
                        {
                            Text = reader.GetString(reader.GetOrdinal("EmployeeName")),
                            Value = reader.GetInt32(reader.GetOrdinal("Id")).ToString()
                        };

                        options.Add(option);

                    }
                    reader.Close();
                    return options;
                }
            }
        }
        private Computer GetComputerById(int id)
        {
            using (SqlConnection conn = Connection)
            {
                conn.Open();
                using (SqlCommand cmd = conn.CreateCommand())
                {
                    cmd.CommandText = @"SELECT c.Id, c.Make, c.Model, c.PurchaseDate, c.DecomissionDate, e.FirstName, e.LastName FROM Computer c 
                                        LEFT JOIN Employee e ON c.Id = e.ComputerId
                                        WHERE c.Id = @id";

                    cmd.Parameters.Add(new SqlParameter("@id", id));

                    var reader = cmd.ExecuteReader();
                    Computer computer = null;

                    if (reader.Read())
                    {
                        computer = new Computer()
                        {
                            Id = reader.GetInt32(reader.GetOrdinal("Id")),
                            Make = reader.GetString(reader.GetOrdinal("Make")),
                            Model = reader.GetString(reader.GetOrdinal("Model")),
                            PurchaseDate = reader.GetDateTime(reader.GetOrdinal("PurchaseDate"))
                        };

                        if (!reader.IsDBNull(reader.GetOrdinal("FirstName")))
                        {
                            computer.Employee = new Employee
                            {
                                FirstName = reader.GetString(reader.GetOrdinal("FirstName")),
                                LastName = reader.GetString(reader.GetOrdinal("LastName"))
                            };
                        }

                    };

                    if (!reader.IsDBNull(reader.GetOrdinal("DecomissionDate")))
                    {
                        computer.DecomissionDate = reader.GetDateTime(reader.GetOrdinal("DecomissionDate"));

                    };




                    reader.Close();
                    return computer;
                }
            }
        }

        private void UpdateEmployee(int computerId, int employeeId)
        {
            using (SqlConnection conn = Connection)
            {
                conn.Open();
                using (SqlCommand cmd = conn.CreateCommand())
                {
                    cmd.CommandText = @"UPDATE Employee
                                            SET ComputerId = @computerId
                                            WHERE Id = @id";

                    cmd.Parameters.Add(new SqlParameter("@computerId", computerId));
                    cmd.Parameters.Add(new SqlParameter("@id", employeeId));

                    cmd.ExecuteNonQuery();
                }
            }
        }
    }
}

Workforce-Purple-Parrots/Workforce-Purple-Parrots/Views/Computers/Create.cshtml
@model Workforce_Purple_Parrots.Models.ViewModels.ComputerFormViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Computer Form</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Make" class="control-label"></label>
                <input asp-for="Make" class="form-control" />
                <span asp-validation-for="Make" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Model" class="control-label"></label>
                <input asp-for="Model" class="form-control" />
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PurchaseDate" class="control-label"></label>
                <input asp-for="PurchaseDate" class="form-control" />
                <span asp-validation-for="PurchaseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmployeeId" class="control-label"></label>
                <select asp-for="EmployeeId" asp-items="@Model.EmployeeOptions" class="form-control">
                    <option>Please Select an Employee</option>
                </select>
                <span asp-validation-for="EmployeeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Workforce-Purple-Parrots/Workforce-Purple-Parrots/Views/Computers/Delete.cshtml
@model Workforce_Purple_Parrots.Models.Computer

@{
    ViewData["Title"] = "Delete";
    
}

<h1>Delete</h1>
@if (ViewData.ContainsKey("ErrorMessage"))
{
<div class="alert alert-danger">@ViewData["ErrorMessage"]</div>
}
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Computer</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PurchaseDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PurchaseDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DecomissionDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DecomissionDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Make)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Make)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Model)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Model)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" />
        <input type="hidden" asp-for="PurchaseDate" class="form-control" />
        <input type="hidden" asp-for="DecomissionDate" class="form-control" />
        <input type="hidden" asp-for="Make" class="form-control" />
        <input type="hidden" asp-for="Model" class="form-control" />
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Workforce-Purple-Parrots/Workforce-Purple-Parrots/Views/Computers/Details.cshtml
@model Workforce_Purple_Parrots.Models.Computer

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Computer</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PurchaseDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PurchaseDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DecomissionDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DecomissionDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Make)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Make)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Model)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Model)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Employee.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Employee.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.LastName)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new {  id = Model.Id  }) |
    <a asp-action="Index">Back to List</a>
</div>

Workforce-Purple-Parrots/Workforce-Purple-Parrots/Views/Computers/Index.cshtml
@model IEnumerable<Workforce_Purple_Parrots.Models.Computer>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form asp-controller="Computers" asp-action="Index">
    <p>
        Search Computers: <input type="text" name="searchString">
        <input type="submit" value="Filter" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PurchaseDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DecomissionDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Make)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Model)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PurchaseDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DecomissionDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Make)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Model)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new {  id=item.Id  }) |
                @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new {  id=item.Id  })
            </td>
        </tr>
}
    </tbody>
</table>